/** Declaration file generated by dts-gen */



declare module 'ansi-escapes' {
	
	export const beep: string

	export const clearScreen: string

	export const cursorGetPosition: string

	export const cursorHide: string

	export const cursorLeft: string

	export const cursorNextLine: string

	export const cursorPrevLine: string

	export const cursorRestorePosition: string

	export const cursorSavePosition: string

	export const cursorShow: string

	export const eraseDown: string

	export const eraseEndLine: string

	export const eraseLine: string

	export const eraseScreen: string

	export const eraseStartLine: string

	export const eraseUp: string

	export const scrollDown: string

	export const scrollUp: string

	export function cursorBackward(count: any): void

	export function cursorDown(count: any): void

	export function cursorForward(count: any): void

	export function cursorMove(x: any, y: any): any

	export function cursorTo(x: any, y: any): any

	export function cursorUp(count: any): void

	export function eraseLines(count: any): any

	export function image(buf: any, opts: any): any

	export function link(text: any, url: any): any

	export namespace iTerm {
		function setCwd(cwd: any): void

	}
	
}


