// /** Declaration file generated by dts-gen */

// declare module 'gun' {

// 	export = gun

// 	function gun(opts?: any): Gun

// 	interface gun {
// 		new(opts?: any): Gun;
// 	}

// 	class Gun {

// 	}

// 	namespace gun {

// 		const version: number

// 		function is(gun: any): boolean

// 	}

// }


