/** Declaration file generated by dts-gen-v2 */

declare module 'rolex' {

	namespace Rolex {

	}
	
	class Rolex {
		static clearInterval(timer?: any): void
		static clearTimeout(timer?: any): void
		static conflict(): void
		static conflictInterval(): void
		static isRolex(obj?: any): any
		static noConflict(): void
		static setInterval(callback?: any, repeat?: any, arg1?: any, arg2?: any, arg3?: any, ...args: any[]): any
		static setTimeout(callback?: any, after?: any, arg1?: any, arg2?: any, arg3?: any, ...args: any[]): any
		constructor(duration?: any, repeat?: any, tick?: any)
		aggression(val?: any, ...args: any[]): any
		count(): any
		duration(val?: any, ...args: any[]): any
		isLastTick(): any
		repeat(val?: any, ...args: any[]): any
		runTime(): any
		start(): any
		startTime(): any
		state(): any
		stop(): any
		threshold(val?: any, ...args: any[]): any
		tick(val?: any, ...args: any[]): any
		tickTime(n?: any): any
	}

	export = Rolex
}

